spring.application.name=CRUD-SpringBoot

# URL de conexión (formato: jdbc:postgresql://host:puerto/nombre_bd)
spring.datasource.url=jdbc:postgresql://localhost:5432/app_clientes

# Credenciales
spring.datasource.username=postgres
spring.datasource.password=Enable01

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate/JPA
# update: actualiza las tablas automáticamente según tus entidades
# create: borra y recrea las tablas cada vez que inicias (cuidado en producción)
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (opcional, muy útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect